version: "3.8"

services:
  client:
    #build:
    #  context: ./client
    image: parthlimbachia1985/emartapp:frontend
    ports:
      - "4200:4200"
    container_name: client
    depends_on:
      - api
      - webapi

  api:
    #build:
    #  context: ./nodeapi
    image: parthlimbachia1985/emartapp:nodeapi
    ports:
      - "5000:5000"
    restart: always
    container_name: api
    depends_on:
      - nginx
      - emongo

  webapi:
    #build:
    #  context: ./javaapi
    image: parthlimbachia1985/emartapp:javaapi
    ports:
      - "9000:9000"
    restart: always
    container_name: webapi
    depends_on:
      - emartdb

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"

  emongo:
    image: mongo:4
    container_name: emongo
    env_file:
      - .env
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    env_file:
      - .env
    ports:
      - "3306:3306"
