apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-javaapi
  namespace: emartapp
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: parthlimbachia1985/emartapp:javaapi
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  namespace: emartapp
spec:
  selector:
    app: webapi
  ports:
  - port: 9000
    targetPort: 9000
