apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
  namespace: emartapp
spec:
  selector:
    matchLabels:
      app: emongo
  replicas: 1
  template:
    metadata:
      labels:
        app: emongo
    spec:
      containers:
      - name: emongo
        image: mongo:4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: emartapp-secret
              key: MONGO_INITDB_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: emongo
  namespace: emartapp
spec:
  selector:
    app: emongo
  ports:
  - port: 27017
    targetPort: 27017
