apiVersion: v1
kind: Secret
metadata:
  name: emartapp-secret
  namespace: emartapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZW1hcnRkYnBhc3M=
  MYSQL_DATABASE: Ym9va3M=
  MONGO_INITDB_DATABASE: ZXBvYw==